name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Push events to version tags v1.0, v2.1.0, etc.
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel setuptools
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Python package
      run: |
        python -m build
        
    - name: Build Windows executable
      run: |
        pyinstaller --name whispa-app --windowed --icon=assets/icon.ico --add-data "assets/*;assets" run.py
        
    - name: Create Windows installer
      run: |
        iscc installer/setup.iss
        
    - name: Run tests
      run: |
        pip install pytest pytest-cov
        pytest tests/ --cov=whispa_app --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
          dist/WhispaApp-Setup.exe
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/* 